#!/bin/bash

#title                    :displayjobs.sh
#description              :This script is for displaying crontab jobs
#author		                :Markus Meresma (40439107)
#date                     :2020.10.05
#version                  :0.1
#Made for		              :CSN08116 2020, coursework
#contributors(1)          :Gabriel Saliev (40441590)
#contributors(2)          :Dávid Gábor Uzonyi(40429825)

#clear terminal
clear

echo "
┌───────────── minute (0 - 59)
│ ┌───────────── hour (0 - 23)
│ │ ┌───────────── day of the month (1 - 31)
│ │ │ ┌───────────── month (1 - 12)
│ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
│ │ │ │ │                                   7 is also Sunday on some systems)
│ │ │ │ │
│ │ │ │ │
* * * * * <command to execute>"

#skip lines with comments and display cronjobs
crontab -l | grep -v "^#"

#execute return to menu script
source `pwd`"/exit"
