#!/bin/bash

#title                    :insertjob.sh                                   
#description              :
#author                   :Gabriel Saliev (40441590)
#date                     :2020.10.15                                                    #version                  :0.1
#Made for                 :CSN08116 2020, coursework                             
#contributors(1)          :Markus Meresma (40439107)                                  
#contributors(2)          :Dávid Gábor Uzonyi(40429825)


echo "
Please insert a job with specified directory(1) or write task(2).
     
examples:
     (1) /home/downloads/.../script_one
     (2) echo hello > /tmp/hello
input:"
read job_input

#do validations, set constraints


#enter minutes
while true;
do
    echo "Enter the minutes (1-59): "
    read minutes

    if [[ minutes -ge 1 ]] && [[ minutes -le 59 ]];
    then
	break
    else
	echo "You must enter a number between 1 and 59."
    fi
done

#enter hour
while true;
do
    echo "Enter the hour (0-23):"
    read hour

    if [[ hour -ge 0 ]] && [[ hour -le 23 ]];
    then
	break
    else
	echo "You must enter a number between 0 and 23."
    fi
done

#enter day of the month

while true;
do
    echo "Enter the day of month (1-31) (enter * for not specified): "
    read day_of_month

    if [[ day_of_month -ge 1 ]] || [[ day_of_month -le 31 ]];
    then
	break
    elif [[ "$day_of_month" == "*" ]] && [[ -z "$day_of_month" ]];
    then
	break
    else
	echo "You must enter a number between 1 and 31."

    fi
done

#enter month of the year

while true;
do
    echo "Enter month of year (1-12) (enter * for not specified): "
    read month_of_year

    if [[ month_of_year -ge 1 ]] && [[ month_of_year -le 12 ]];
    then
	break
    elif [[ "$month_of_year" == "*" ]] || [[ -z "$month_of_year" ]];
    then
	break
    else
	echo "You must enter a number between 1 and 12."
    fi
done

#enter day of the week

while true;
do
    echo "Enter day of week (1-7) (enter * for not specified): "
    read day_of_week

    if [[ day_of_week -ge 1 ]] && [[ day_of_week -le 7 ]];
    then
	break
    elif [[ "$day_of_week" == "*" ]] || [[ -z "$day_of_week" ]];
    then
	break
    else
	echo "You must enter a number between 1 and 7."
    fi
done

job_format="$minutes $hour $day_of_month $month_of_year $day_of_week $job_input"

(crontab -l ; echo $job_format)| crontab -

echo "Crontab created successfully!"

source `pwd`"/exit"
