#!/bin/bash

#title                    :insertjob.sh                                   
#description              :
#author                   :Gabriel Saliev (40441590),Dávid Gábor Uzonyi(40429825)
#date                     :2020.10.15                                                    
#version                  :0.1
#Made for                 :CSN08116 2020, coursework                             
#contributors(1)          :Markus Meresma (40439107)                                  



echo "
Please insert a job with specified directory(1) or write task(2).
     
examples:
     (1) /home/downloads/.../script_one
     (2) echo hello > /tmp/hello
input:"

#validation  
read job_input


function valadtion(){


function user_interaction  () {
 
echo -n $Text
read user_input
validat
}
  
function validat(){
if  [ $user_input -gt $greater_than ]  &&  [ $user_input -lt $Less_than ]
then
	echo "all good , delet later!!!"
else
	printf "The number is not Greater than $greater_than or not Less than $Less_than"
	echo
	user_interaction
fi
}


#call user_interaction function 
user_interaction

}



#Get the minutes from the user
#Passing parameters to the function
Text="Please enter minutes after hour (0-60): "
greater_than=0
Less_than=61
#call valadtion function
valadtion
minutes=$user_input


#Get the hour from the user
#Passing parameters to the function
Text="Please enter hour (0-24):  "
greater_than=0
Less_than=25
#call valadtion function
valadtion 
hour=$user_input



#Get the day of month from the user
#Passing parameters to the function
Text="Please enter day of month (1-30) (* for not specified): "
greater_than=0
Less_than=32
#call valadtion function
valadtion
day=$user_input



#Get the day of month from the user
#Passing parameters to the function
Text="Please enter day of the week (1-7) (* for not specified):"
greater_than=0
Less_than=8
#call valadtion function
valadtion
day_of_week=$user_input




#Get the day of month from the user
#Passing parameters to the function
Text="Please enter month of year (1-12) (* for not specified):"
greater_than=0
Less_than=13
#call valadtion function
valadtion 
month_of_year=$user_input



#if day of the week is specified
#make day_of_year and day_of_month stars * *

job_format="$minutes $hour $day_of_month $month_of_year $day_of_week $job_input"

(crontab -l ; echo $job_format)| crontab -

echo "Crontab created successfully!"

source `pwd`"/exit"


