#!/bin/bash

#title                    :menu.sh
#description              :This script is the for usere interaction .
#author		          :Dávid Gábor Uzonyi(40429825)
#date                     :2020.10.05
#version                  :0.1
#Made for		  :CSN08116 2020, coursework
#contributors(1)          :Markus Meresma (40439107)
#contributors(2)          :Gabriel Saliev (40441590)
#

#The menu function is the first interaction with the user.
#The function calls the corresponding task.


display_job_wd+=`pwd`"/displayjob"
insert_job_wd=`pwd`"/insertjob"
edit_job_wd=`pwd`"/editjob"
remove_job_wd=`pwd`"/removejob"
remove_all_jobs_wd=`pwd`"/removealljobs"

function menu () {
numchoice=1
while [ $numchoice != 0 ]; do
 echo -n "
 1. Display crontab jobs
 2. Insert a job
 3. Edit a job
 4. Remove a job
 5. Remove all jobs
 0. Exit
 enter choice [1 | 2 | 3 | 4 | 5 | 0]: "
 read numchoice
 case $numchoice in
     "1" ) source $display_job_wd
           break;;# call displaying cron function ....
     "2" ) source $insert_job_wd
           break;;# call inser job  function ....
     "3" ) source $edit_job_wd
           break;;
     "4" ) source $remove_job_wd
           break;;
     "5" ) source $remove_all_jobs_wd
	   break;;
     "0" ) break ;;
     * ) echo -n "You entered an incorrect option. Please try again." ;;
 esac
done
}

menu
