#!/bin/bash

#title                    :mycrontab.sh
#description              :This script for usere interaction 
#author		              :Dávid Gábor Uzonyi(40429825)
#date                     :2020.10.05
#version                  :0.1
#Made for		          :CSN08116 2020, coursework
#contributors(1)          :Markus Meresma (40439107)
#contributors(2)          :Gabriel Saliev (40441590)
#


#function definitions
display_job_wd=`pwd`"/displayjob"
insert_job_wd=`pwd`"/insertjob"
edit_job_wd=`pwd`"/editjob"
remove_job_wd=`pwd`"/removejob"
remove_all_jobs_wd=`pwd`"/removealljobs"
exit_wd=`pwd`"/exit"


#The menu function is the first interaction with the user.
#The function calls the corresponding task.
function menu () {
numchoice=1
while [ $numchoice != 0 ]; do
clear	

echo "
 ###  ### ###    ###   :####:  ######:    .####.   ###   ## 
 ###  ### .##:  :##.   ######  #######    ######   ###   ## 
 ###::###  ###  ###  :##:  .#  ##   :##  :##  ##:  ###:  ## 
 ###  ###   ##::##   ##        ##    ##  ##:  :##  ####  ## 
 ## ## ##    ####    ##.       ##   :##  ##    ##  ##:#: ## 
 ##:##:##    ####    ##        #######:  ##    ##  ## ## ## 
 ##.##.##    :##:    ##        ######    ##    ##  ## ## ## 
 ## ## ##     ##     ##.       ##   ##.  ##    ##  ## :#:## 
 ##    ##     ##     ##        ##   ##   ##:  :##  ##  #### 
 ##    ##     ##     :##:  .#  ##   :##  :##  ##:  ##  :### 
 ##    ##     ##       ######  ##    ##:  ######   ##   ### 
 ##    ##     ##       :####:  ##    ###  .####.   ##   ### 

"

echo -n "
Please select an option from the menu: 

 1. Display crontab jobs
 2. Insert a job
 3. Edit a job
 4. Remove a job
 5. Remove all jobs
 6. Help
 0. Exit
 
 Enter choice [1 | 2 | 3 | 4 | 5 | 6 | 0]: "
 read numchoice
 case $numchoice in
     "1" ) source $display_job_wd
           break;;
     "2" ) source $insert_job_wd
           break;;
     "3" ) source $edit_job_wd
           break;;
     "4" ) source $remove_job_wd
           break;;
     "5" ) source $remove_all_jobs_wd
	   break;;
      "6" ) cat README.md  ; source $exit_wd
	   break;;
     "0" ) exit 0;;
     * ) echo -n "You entered an incorrect option. Please try again." ;;
 esac
done 
} 

menu
