#!/bin/bash

#title                    :removejob
#description              :This script is for removing a cronjob
#author                   :Markus Meresma (40439107)
#date                     :2020.10.05
#version                  :0.1
#Made for                 :CSN08116 2020, coursework
#contributors(1)          :Gabriel Saliev (40441590)
#contributors(2)          :Dávid Gábor Uzonyi(40429825)


#clear the terminal
clear 

echo "Current cronjobs: "
echo ""

#displayjobs
crontab -l | grep -v "^#"
echo ""

while true
do
	echo "Please insert the command of the job you would like to remove ('exit' to return to main menu or 'end' to terminate the program: "
	read job

	case $job in
		"exit")
			#clear the terminal and return to main menu
			clear
			source `pwd`"/menu"
			;;
		"end")
			#terminate the program
			exit 0
			;;
		"")
			echo "No input detected"
			continue
			;;
		*)
			#search for the command in cronjob file
			if crontab -l | grep "$job"
			then
				crontab -l | sed "/$job/d" | crontab -
				echo "The job you want to remove exists in the file and is now deleted"
				break
			else
				echo "The job you want to remove does not exist in the file"
			fi
			;;
	esac
done

#use return script
source `pwd`"/exit"

