#!/bin/bash

#title                    :removejob
#description              :This script is for removing a cronjob
#author                   :Markus Meresma (40439107)
#date                     :2020.10.05
#version                  :0.1
#Made for                 :CSN08116 2020, coursework
#contributors(1)          :Gabriel Saliev (40441590)
#contributors(2)          :Dávid Gábor Uzonyi(40429825)

#function to remove a job
function remove_a_job(){
	
#clear the terminal
clear 

echo "List of current cronjobs: "
echo ""

#displayjobs
crontab -l | grep -v "^#"
echo ""

while true
do
	echo "Please insert the command of the job you would like to remove (e.g. * 12 1 * 1 /home/test/bin/check-db-status)
Type 'exit' to return to main menu or 'end' to terminate the program"
	read job

	case $job in
		"exit")
			#clear the terminal and return to main menu
			clear
			source `pwd`"/menu"
			;;
		"end")
			#terminate the program
			exit 0
			;;
		"")
			echo "No input detected"
			continue
			;;
		*)
			#call the function which handles deletion
			search_and_delete $job
			;;
	esac
done
}

#function to search for a cronjob and delete it
function search_and_delete(){
	
	#search for the command in cronjob file
	if crontab -l | grep $1
	then
		echo "Cronjob found. Are you sure you want to delete it? (Y/N)"
		read answer
		if [[ "$answer" == "Y" ]]
		then
			crontab -l | sed "/1/d" | crontab -
			echo "Cronjob deleted"
		fi
	else
		echo "The job you want to remove does not exist in the file"
	fi
}

#should be called from different script
remove_a_job

#use exit script
source `pwd`"/exit"

