#!/bin/bash

#title                    :removejob
#description              :This script is for removing a cronjob
#author                   :Markus Meresma (40439107)
#date                     :2020.10.05
#version                  :0.1
#Made for                 :CSN08116 2020, coursework
#contributors(1)          :Gabriel Saliev (40441590)
#contributors(2)          :Dávid Gábor Uzonyi(40429825)

#clear the terminal
clear

#loop while there are cronjobs to remove, if no cronjobs then display a message
function check_cronjobs(){

	
	#count the lines without comments in crontab file
	var=$(crontab -l | grep -cv "^#")

	while [ $var -gt 0 ]
	do
		echo "List of current cronjobs: "
                echo ""
                crontab -l | grep -v "^#" #displayjobs
		echo ""
                remove_a_job #call the function
		var=$(crontab -l | grep -cv "^#")
	done

	echo "No cronjobs to remove"
	echo ""
}

#function to remove a job
function remove_a_job(){ 

	choice=1
	while [ $choice != 0 ]; do
		echo "Please insert the command of the job you would like to remove (e.g. /home/test/bin/check-db-status) [You can also type 'exit' to return to main menu or 'end' to terminate the program]"
		read job

		case $job in
			"exit")
				#clear the terminal and return to main menu
				clear
				source `pwd`"/mycrontab"
				;;
			"end")
				#terminate the program
				exit 0
				;;
			"")
				echo "No input detected"
				echo ""
				continue
				;;
			*)
				#call the function which handles deletion
				choice=0
				search_and_delete $job
				;;
		esac
	done
}

#function to search for a cronjob and delete it
function search_and_delete(){
	
	#search for the cronjob in the crontab
	var=$(crontab -l | grep -c $1)

	#search for the cronjob
	if [ $var -gt 0 ]
	then
		#save the cronjob to a variable
		cronjob=$(crontab -l | grep $1)
		choice=1

		#loop until user enters Y/N
		while [ $choice != 0 ]; do
			echo "Cronjob found. Are you sure you want to delete it? (Y/N)"
			read answer
			
			case $answer in
				"Y") 
					#delete the cronjob
					crontab -u $USER -l | grep -v "$cronjob" | crontab -u $USER -
					echo "Cronjob deleted"
                                	echo ""
					choice=0 #set choice flag to 0
					;;
				"N")
					choice=0 #set choice flag to 0
					echo ""
					;;
				"*")
					continue
					;;
			esac
		done
	else
		#display error message if there is no cronjob in the file
		echo "The job you want to remove does not exist in the file"
		echo ""
	fi
}

#call the check_cronjobs function - executes the script
check_cronjobs

#use exit script
source `pwd`"/exit"

