#!/bin/bash

#title                :menu.sh
#description          :This script for remove all jobs  
#author               :Dávid Gábor Uzonyi(40429825)
#date                 :2020.10.05
#version              :Pre-alpha
#Made for		          :CSN08116 2020, coursework
#contributors(1)      :Markus Meresma (40439107)
#contributors(2)      :Gabriel Saliev (40441590)
#

function remove_all_jobs () {
  clear #clear the terminal 
  echo  -e "Are you sure you want to REMOVE ALL THE JOBS?" 
  echo -n "Enter yes or no:"

  read user_input #read the user input

}

function input_validation(){
while true; do #while loop for error handling
  remove_all_jobs

 if [ $user_input == "yes" ] 
 then
    crontab -r #removes all crontab jobs
 break 

 elif [  $user_input == "no" ]; 
    then
   	printf "Jobs will not be removed"
 break

 else #else statement for not valid input
      printf "This is not a valid option %s\n" "$user_input"
   echo

  fi
done
}

input_validation


#execute return to menu script
source `pwd`"/exit"

exit 0


